# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4fb1b304062d078d158521a516678de61233ad90c64d5c85bd435f701cc54a22ce30bde2ee79aee539680205a80de21707745fe7af252c2eb472ae47058bc5d

test:
  secret_key_base: f3d7b2f20efd0085fe6ef0ec95d12e94dcacac83fe2ef3a11ee7802c38bad68dd820fbd8241db7a900f1a702d27d42b0ea665d775cd994ef3b7bbbe782451be9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
